version: "3.5"

services:
 anokap:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - JEKYLL_ENV=dev
    ports:
      - 4001:4000
    container_name: anokap
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t --config _config_dev.yml
